//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMG_IIA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("サービスアカウントで作成したサービス名")]
        public string GoogleAPIApplicationName {
            get {
                return ((string)(this["GoogleAPIApplicationName"]));
            }
            set {
                this["GoogleAPIApplicationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("サービスアカウントで作成した鍵(json形式)のファイルパスを指定")]
        public string GoogleAPICredentialsPath {
            get {
                return ((string)(this["GoogleAPICredentialsPath"]));
            }
            set {
                this["GoogleAPICredentialsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("画像をアップロードするフォルダIDを指定")]
        public string GoogleAPIDriveParentId {
            get {
                return ((string)(this["GoogleAPIDriveParentId"]));
            }
            set {
                this["GoogleAPIDriveParentId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpn")]
        public string TrainingModelLanguage {
            get {
                return ((string)(this["TrainingModelLanguage"]));
            }
            set {
                this["TrainingModelLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ja")]
        public string OCRLanguage {
            get {
                return ((string)(this["OCRLanguage"]));
            }
            set {
                this["OCRLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double MATCH_THRESHOLD {
            get {
                return ((double)(this["MATCH_THRESHOLD"]));
            }
            set {
                this["MATCH_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mTemp/")]
        public string MATCH_TEMP_DIR {
            get {
                return ((string)(this["MATCH_TEMP_DIR"]));
            }
            set {
                this["MATCH_TEMP_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("char_pm_gvs/")]
        public string MATCH_GUILDVS_CHARACTER_DIR {
            get {
                return ((string)(this["MATCH_GUILDVS_CHARACTER_DIR"]));
            }
            set {
                this["MATCH_GUILDVS_CHARACTER_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div/")]
        public string MATCH_TEMP_DIV_DIR {
            get {
                return ((string)(this["MATCH_TEMP_DIV_DIR"]));
            }
            set {
                this["MATCH_TEMP_DIV_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("char_icon/")]
        public string FormationCharaImagePath {
            get {
                return ((string)(this["FormationCharaImagePath"]));
            }
            set {
                this["FormationCharaImagePath"] = value;
            }
        }
    }
}
